version: "3.2"
services:
  sepma_pinger:
    container_name: "sepma_pinger"
    build:
      context: "."
    environment:
      WEBHOOK_ID: "someId"
      WEBHOOK_TOKEN: "someToken"
    volumes:
      - ./data:/app/data
